Repository Co-Laon/claon-admin-server, pull requests merged in 2023-06, with the labels that each got.

#137 refac: add annotated and change optional to multiple typing
  claon_admin/common/annotated.py
  claon_admin/common/util/redis.py
  claon_admin/model/admin.py
  claon_admin/model/auth.py
  claon_admin/model/center.py
  claon_admin/model/review.py
  claon_admin/model/user.py
  claon_admin/router/admin.py
  claon_admin/router/auth.py
  claon_admin/router/center.py
  claon_admin/router/user.py
  claon_admin/schema/center.py
  claon_admin/schema/post.py
  claon_admin/service/center.py
  pyproject.toml
Labels: refactor

#134 feat: add rabbitmq and celery configs
  .gitignore
  README.md
  claon_celery/__init__.py
  claon_celery/celery.py
  claon_celery/configs.py
  claon_celery/tasks.py
  docker-compose.yml
  pyproject.toml
Labels: enhancement

#138 feat: add time mixin for created at
  claon_admin/common/util/db.py
  claon_admin/schema/center.py
  claon_admin/schema/post.py
  claon_admin/schema/user.py
Labels: enhancement

#141 feat: add find center by id
  claon_admin/router/center.py
  claon_admin/schema/center.py
  claon_admin/service/center.py
  tests/service/center/test_find_by_id.py
Labels: enhancement, fix

#142 [WIP] refactor code about dependency
  .coveragerc
  claon_admin/common/annotated.py
  claon_admin/common/consts.py
  claon_admin/common/util/auth.py
  claon_admin/common/util/jwt.py
  claon_admin/common/util/pagination.py
  claon_admin/common/util/time.py
  claon_admin/config/config.py
  claon_admin/container.py
  claon_admin/main.py
  claon_admin/model/center.py
  claon_admin/model/user.py
  claon_admin/service/center.py
  claon_admin/service/oauth.py
  claon_admin/service/user.py
  tests/service/center/conftest.py
  tests/service/center/test_find_centers.py
  tests/service/center/test_find_posts_by_center.py
  tests/service/center/test_find_reviews_by_center.py
  tests/service/user/conftest.py
  tests/service/user/test_sign_in.py
Labels: refactor

#144 feat: delete center
  claon_admin/common/error/exception.py
  claon_admin/model/center.py
  claon_admin/router/center.py
  claon_admin/schema/center.py
  claon_admin/service/center.py
  tests/repository/center/test_center.py
  tests/service/center/conftest.py
  tests/service/center/test_delete.py
Labels: enhancement

#147 refac: add abstract repository and remove static method
  .pylintrc
  claon_admin/common/util/repository.py
  claon_admin/model/center.py
  claon_admin/schema/center.py
  claon_admin/schema/post.py
  claon_admin/schema/user.py
  claon_admin/service/admin.py
  claon_admin/service/center.py
  tests/repository/center/test_center.py
  tests/repository/center/test_review.py
  tests/repository/user/test_lector.py
  tests/repository/user/test_user.py
  tests/service/admin/test_approve_center.py
  tests/service/admin/test_reject_center.py
  tests/service/center/test_find_by_id.py
  tests/service/center/test_find_posts_by_center.py
Labels: refactor

#148 feat: add api for both member and membership (#88)
  claon_admin/common/enum.py
  claon_admin/container.py
  claon_admin/main.py
  claon_admin/model/membership.py
  claon_admin/router/center.py
  claon_admin/router/membership.py
  claon_admin/service/membership.py
Labels: enhancement

#151 fix: fix bug about model and container in membership
  claon_admin/model/membership.py
  claon_admin/router/center.py
  claon_admin/router/membership.py
  claon_admin/service/center.py
  tests/service/center/conftest.py
  tests/service/center/test_find_posts_summary_by_center.py
Labels: fix

#154 refac: refactor center hold dto format
  claon_admin/model/admin.py
  claon_admin/model/center.py
  claon_admin/service/center.py
  claon_admin/service/user.py
  tests/service/center/test_delete.py
  tests/service/center/test_update.py
  tests/service/user/test_sign_up_center.py
Labels: refactor
