Repository Co-Laon/claon-admin-server, pull requests merged in 2023-03, with the labels that each got.

#1 chore: add issue and pull request templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/QUESTION.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
Labels: chore

#4 chore: init fastapi project using poetry
  .gitignore
  README.md
  claon_admin/__init__.py
  claon_admin/config/__init__.py
  claon_admin/config/config.py
  claon_admin/config/consts.py
  claon_admin/container.py
  claon_admin/main.py
  claon_admin/model/__init__.py
  claon_admin/router/__init__.py
  claon_admin/schema/__init__.py
  claon_admin/schema/conn.py
  claon_admin/service/__init__.py
  docker-compose.yml
  pyproject.toml
  tests/__init__.py
Labels: chore

#6 chore: add db config for prod environment
  .gitignore
  claon_admin/config/config.py
Labels: chore

#11 feat: add example code and test code
  .gitignore
  claon_admin/config/config.py
  claon_admin/container.py
  claon_admin/main.py
  claon_admin/model/example.py
  claon_admin/router/example.py
  claon_admin/schema/conn.py
  claon_admin/schema/example.py
  claon_admin/service/example.py
  pyproject.toml
  pytest.ini
  tests/conftest.py
  tests/repository/__init__.py
  tests/repository/test_example.py
  tests/service/__init__.py
  tests/service/test_example.py
Labels: enhancement

#12 refac: refactor to be possible without prod config
  claon_admin/config/config.py
Labels: refactor

#13 refac: refactor config for test code
  tests/conftest.py
Labels: refactor

#26 chore: add contributing guideline
  CONTRIBUTING.md
Labels: chore

#29 feat: add request, response logger
  .coveragerc
  claon_admin/config/log.py
  claon_admin/main.py
  claon_admin/middleware/__init__.py
  claon_admin/middleware/log.py
  logging.conf
Labels: enhancement

#27 feat: add error code and exception handler (#17)
  .coveragerc
  claon_admin/common/__init__.py
  claon_admin/common/error/__init__.py
  claon_admin/common/error/exception.py
  claon_admin/common/error/handler.py
  claon_admin/main.py
Labels: enhancement

#32 feat: add config by environment
  claon_admin/config/config.py
  claon_admin/config/consts.py
Labels: enhancement

#33 fix: fix bug about config
  claon_admin/config/config.py
Labels: fix
