Repository Co-Laon/claon-admin-server, pull requests merged in 2023-05, with the labels that each got.

#76 feat: implement feature for find posts by center (#57)
  claon_admin/container.py
  claon_admin/main.py
  claon_admin/model/post.py
  claon_admin/router/auth.py
  claon_admin/router/center.py
  claon_admin/schema/center.py
  claon_admin/schema/user.py
  claon_admin/service/center.py
  claon_admin/service/user.py
  tests/repository/test_center.py
  tests/service/test_center.py
Labels: enhancement

#81 feat: add user profile upload method (#78)
  claon_admin/common/error/exception.py
  claon_admin/main.py
  claon_admin/model/user.py
  claon_admin/router/user.py
  claon_admin/service/user.py
  tests/service/test_user.py
Labels: enhancement

#77 feat: check unapproved lectors and centers
  claon_admin/config/auth.py
  claon_admin/container.py
  claon_admin/main.py
  claon_admin/model/admin.py
  claon_admin/model/auth.py
  claon_admin/model/center.py
  claon_admin/router/admin.py
  claon_admin/router/center.py
  claon_admin/schema/center.py
  claon_admin/schema/user.py
  claon_admin/service/admin.py
  tests/repository/test_center.py
  tests/repository/test_user.py
  tests/service/test_admin.py
  tests/service/test_user.py
Labels: enhancement

#82 feat: add find review by tag and answer or not (#59)
  claon_admin/common/error/exception.py
  claon_admin/container.py
  claon_admin/model/review.py
  claon_admin/router/center.py
  claon_admin/schema/center.py
  claon_admin/service/center.py
  tests/repository/test_center.py
  tests/service/test_center.py
Labels: enhancement

#84 feat: add create, update, delete review answer (#60)
  claon_admin/container.py
  claon_admin/model/review.py
  claon_admin/router/center.py
  claon_admin/schema/center.py
  claon_admin/service/center.py
  tests/repository/test_center.py
  tests/service/test_center.py
Labels: enhancement

#96 fix: fix config parameter about redis
  claon_admin/config/config.py
Labels: fix

#97 fix: fix bug about generation uuid pk automatically
  claon_admin/schema/center.py
  claon_admin/schema/user.py
  claon_admin/service/user.py
Labels: fix

#100 feat: add upload file in s3 for lector (#93)
  claon_admin/common/enum.py
  claon_admin/model/center.py
  claon_admin/model/file.py
  claon_admin/router/center.py
  claon_admin/router/user.py
  claon_admin/service/user.py
  tests/service/test_user.py
Labels: enhancement

#104 fix: fix bug about request user validate
  claon_admin/config/auth.py
  claon_admin/model/auth.py
  claon_admin/schema/user.py
  tests/service/test_admin.py
  tests/service/test_user.py
Labels: fix

#105 fix: fix bug when calling sign in, sign up redundantly
  claon_admin/common/enum.py
  claon_admin/schema/center.py
  claon_admin/schema/user.py
  claon_admin/service/user.py
Labels: fix

#106 feat: add stacktrace to log
  claon_admin/common/error/handler.py
Labels: enhancement

#90 feat: search center by name
  claon_admin/model/center.py
  claon_admin/router/center.py
  claon_admin/schema/center.py
  claon_admin/service/center.py
  tests/repository/test_center.py
  tests/service/test_center.py
Labels: enhancement

#110 feat: add middleware for file limit check
  claon_admin/common/error/exception.py
  claon_admin/main.py
  claon_admin/middleware/file.py
Labels: enhancement

#111 feat: add page for log visualization
  claon_admin/config/config.py
  claon_admin/main.py
  claon_admin/middleware/log.py
  claon_admin/router/index.py
  claon_admin/template/log.html
  pyproject.toml
Labels: enhancement

#119 feat: add util for convert relative time
  claon_admin/common/util/time.py
  claon_admin/model/post.py
  claon_admin/model/review.py
  claon_admin/model/user.py
  claon_admin/service/center.py
  tests/service/test_center.py
Labels: enhancement

#94 feat: add find post summary dashboard (#56)
  claon_admin/common/util/counter.py
  claon_admin/model/post.py
  claon_admin/router/center.py
  claon_admin/schema/center.py
  claon_admin/service/center.py
  pyproject.toml
  tests/repository/test_center.py
  tests/service/test_center.py
Labels: enhancement

#120 feat: add rotating file handler for log
  .gitignore
  claon_admin/router/index.py
  claon_admin/template/log.html
  logging.conf
Labels: enhancement

#122 fix: refactor validation about center admin
  .pylintrc
  claon_admin/router/admin.py
  claon_admin/router/center.py
  claon_admin/router/user.py
  claon_admin/service/center.py
  tests/service/test_center.py
Labels: fix

#124 refac: refactor directory structure for test
  pyproject.toml
  tests/conftest.py
  tests/repository/center/__init__.py
  tests/repository/center/conftest.py
  tests/repository/center/test_center.py
  tests/repository/conftest.py
  tests/repository/user/__init__.py
  tests/repository/user/conftest.py
  tests/repository/user/test_user.py
  tests/service/admin/__init__.py
  tests/service/admin/conftest.py
  tests/service/admin/test_admin.py
  tests/service/center/__init__.py
  tests/service/center/conftest.py
  tests/service/center/test_center.py
  tests/service/conftest.py
  tests/service/user/__init__.py
  tests/service/user/conftest.py
  tests/service/user/test_user.py
Labels: refactor

#129 fix: fix bug about center and search option
  claon_admin/model/center.py
  claon_admin/router/center.py
  claon_admin/schema/center.py
  claon_admin/service/user.py
  tests/repository/center/conftest.py
  tests/repository/center/test_center.py
  tests/service/center/conftest.py
  tests/service/user/test_user.py
Labels: fix

#123 feat: add find centers for center admin (#55)
  claon_admin/model/center.py
  claon_admin/router/center.py
  claon_admin/schema/center.py
  claon_admin/service/center.py
  tests/repository/center/conftest.py
  tests/repository/center/test_center.py
  tests/service/center/conftest.py
  tests/service/center/test_center.py
Labels: enhancement

#130 refac: seperate test file
  claon_admin/service/admin.py
  pyproject.toml
  pytest.ini
  tests/repository/center/conftest.py
  tests/repository/center/test_center.py
  tests/repository/center/test_center_approved_file.py
  tests/repository/center/test_center_fee.py
  tests/repository/center/test_center_hold.py
  tests/repository/center/test_center_wall.py
  tests/repository/center/test_post.py
  tests/repository/center/test_review.py
  tests/repository/user/test_lector.py
  tests/repository/user/test_lector_approved_file.py
  tests/repository/user/test_user.py
  tests/service/admin/conftest.py
  tests/service/admin/test_admin.py
  tests/service/admin/test_approve_center.py
  tests/service/admin/test_approve_lector.py
  tests/service/admin/test_get_unapproved_centers.py
  tests/service/admin/test_get_unapproved_lectors.py
  tests/service/admin/test_reject_center.py
  tests/service/admin/test_reject_lector.py
  tests/service/center/conftest.py
  tests/service/center/test_center.py
  tests/service/center/test_create_review_answer.py
  tests/service/center/test_delete_review_answer.py
  tests/service/center/test_find_centers.py
  tests/service/center/test_find_centers_by_name.py
  tests/service/center/test_find_posts_by_center.py
  tests/service/center/test_find_posts_summary_by_center.py
  tests/service/center/test_find_reviews_by_center.py
  tests/service/center/test_update_review_answer.py
  tests/service/center/test_upload_file.py
  tests/service/user/conftest.py
  tests/service/user/test_check_nickname_duplication.py
  tests/service/user/test_sign_in.py
  tests/service/user/test_sign_up_center.py
  tests/service/user/test_sign_up_lector.py
  tests/service/user/test_upload_file.py
  tests/service/user/test_upload_profile.py
  tests/service/user/test_user.py
Labels: refactor

#133 feat: add scheduler that counts the number of posts by center per day
  .coveragerc
  claon_admin/job/__init__.py
  claon_admin/job/post.py
  claon_admin/main.py
  claon_admin/schema/center.py
  claon_admin/schema/post.py
  pyproject.toml
  tests/repository/center/conftest.py
  tests/repository/center/test_center.py
  tests/repository/post/conftest.py
  tests/repository/post/test_post.py
Labels: enhancement, refactor

#135 fix: fix bug about calculate week of post dashboard
  claon_admin/model/post.py
  claon_admin/service/center.py
  tests/service/center/test_find_posts_summary_by_center.py
Labels: fix
