Repository Co-Laon/claon-admin-server, pull requests merged in 2023-04, with the labels that each got.

#35 refac: refactor logger for get http method
  claon_admin/middleware/log.py
Labels: refactor

#36 feat: add example code for attribute converter
  claon_admin/model/example.py
  claon_admin/schema/example.py
  claon_admin/service/example.py
  tests/service/test_example.py
Labels: enhancement

#34 feat: S3 utils
  claon_admin/common/s3.py
  claon_admin/config/consts.py
  claon_admin/container.py
  pyproject.toml
Labels: enhancement

#31 feat: add jwt filter
  .coveragerc
  .github/codecov.yml
  claon_admin/common/error/exception.py
  claon_admin/common/util/__init__.py
  claon_admin/common/util/header.py
  claon_admin/common/util/jwt.py
  claon_admin/config/consts.py
  claon_admin/container.py
  claon_admin/main.py
  claon_admin/schema/conn.py
  claon_admin/schema/user.py
  pyproject.toml
  tests/repository/test_user.py
Labels: enhancement

#39 refac: refactor code about jwt and authentication
  claon_admin/common/util/header.py
  claon_admin/common/util/jwt.py
  claon_admin/main.py
Labels: refactor

#37 feat: add user, center schema (#25)
  claon_admin/schema/center.py
  claon_admin/schema/user.py
  tests/conftest.py
  tests/repository/test_center.py
  tests/repository/test_user.py
Labels: enhancement

#42 feat: add admin api for #24
  claon_admin/main.py
  claon_admin/model/admin.py
  claon_admin/model/enum.py
  claon_admin/model/user.py
  claon_admin/router/admin.py
Labels: enhancement

#41 feat: add redis config and refac to save refresh token to redis
  claon_admin/common/util/jwt.py
  claon_admin/common/util/redis.py
  claon_admin/common/util/s3.py
  claon_admin/config/config.py
  claon_admin/config/redis.py
  claon_admin/container.py
  docker-compose.yml
  pyproject.toml
Labels: enhancement

#44 refac: add approve column into user table for admin (#43)
  claon_admin/schema/center.py
  claon_admin/schema/user.py
  tests/conftest.py
  tests/repository/test_center.py
  tests/repository/test_user.py
Labels: refactor

#47 refac: refactor code for cyclic dependency and test code
  .gitignore
  claon_admin/common/util/jwt.py
  claon_admin/config/auth.py
  claon_admin/model/auth.py
  test_config.ini
  tests/repository/test_center.py
  tests/repository/test_example.py
  tests/service/test_example.py
Labels: refactor

#46 feat: sign-up lector and center admin
  claon_admin/common/error/exception.py
  claon_admin/container.py
  claon_admin/model/center.py
  claon_admin/model/enum.py
  claon_admin/model/user.py
  claon_admin/router/auth.py
  claon_admin/schema/center.py
  claon_admin/schema/user.py
  claon_admin/service/user.py
  tests/conftest.py
  tests/repository/fixtures.py
  tests/repository/test_center.py
  tests/repository/test_user.py
  tests/service/test_user.py
Labels: enhancement

#62 refac: remove example code
  claon_admin/container.py
  claon_admin/main.py
  claon_admin/model/example.py
  claon_admin/router/example.py
  claon_admin/schema/example.py
  claon_admin/service/example.py
  tests/repository/test_example.py
  tests/service/test_example.py
Labels: refactor

#66 feat: add kakao oauth (#20)
  claon_admin/container.py
  claon_admin/infra/provider.py
  tests/service/test_user.py
Labels: enhancement

#63 feat: climbing information API
  claon_admin/main.py
  claon_admin/model/admin.py
  claon_admin/model/center.py
  claon_admin/model/post.py
  claon_admin/model/review.py
  claon_admin/model/user.py
  claon_admin/router/auth.py
  claon_admin/router/center.py
  claon_admin/router/user.py
  claon_admin/service/user.py
  tests/service/test_user.py
Labels: enhancement

#67 feat: add pagination (#61)
  claon_admin/common/util/pagination.py
  claon_admin/container.py
  claon_admin/main.py
  claon_admin/router/auth.py
  claon_admin/schema/center.py
  claon_admin/schema/user.py
  claon_admin/service/user.py
  pyproject.toml
  tests/service/test_user.py
Labels: enhancement

#65 feat: approve/reject lector and center
  claon_admin/common/error/exception.py
  claon_admin/common/util/s3.py
  claon_admin/container.py
  claon_admin/main.py
  claon_admin/model/admin.py
  claon_admin/model/center.py
  claon_admin/model/user.py
  claon_admin/router/admin.py
  claon_admin/schema/center.py
  claon_admin/schema/user.py
  claon_admin/service/admin.py
  claon_admin/service/user.py
  tests/conftest.py
  tests/repository/fixtures.py
  tests/repository/test_center.py
  tests/repository/test_user.py
  tests/service/test_admin.py
  tests/service/test_user.py
Labels: enhancement

#70 refac: refactor ondelete cascade of db relationship
  claon_admin/schema/center.py
  claon_admin/schema/user.py
Labels: refactor

#71 feat: add sign in using oauth id for test
  claon_admin/router/auth.py
  claon_admin/schema/user.py
  claon_admin/service/user.py
  tests/repository/test_user.py
Labels: enhancement

#72 feat: add post, review table (#54)
  claon_admin/container.py
  claon_admin/model/admin.py
  claon_admin/model/center.py
  claon_admin/model/enum.py
  claon_admin/model/post.py
  claon_admin/schema/center.py
  claon_admin/service/user.py
  tests/repository/test_center.py
  tests/repository/test_user.py
  tests/service/test_admin.py
  tests/service/test_user.py
Labels: enhancement, refactor

#73 refac: refactor config structure
  claon_admin/common/enum.py
  claon_admin/common/util/db.py
  claon_admin/common/util/jwt.py
  claon_admin/common/util/oauth.py
  claon_admin/common/util/redis.py
  claon_admin/common/util/s3.py
  claon_admin/config/auth.py
  claon_admin/config/config.py
  claon_admin/config/consts.py
  claon_admin/config/env.py
  claon_admin/config/redis.py
  claon_admin/config/s3.py
  claon_admin/container.py
  claon_admin/infra/__init__.py
  claon_admin/main.py
  claon_admin/model/admin.py
  claon_admin/model/auth.py
  claon_admin/model/center.py
  claon_admin/model/user.py
  claon_admin/router/admin.py
  claon_admin/router/auth.py
  claon_admin/router/center.py
  claon_admin/router/user.py
  claon_admin/schema/center.py
  claon_admin/schema/user.py
  claon_admin/service/admin.py
  claon_admin/service/user.py
  test_config.ini
  tests/conftest.py
  tests/repository/test_center.py
  tests/repository/test_user.py
  tests/service/test_admin.py
  tests/service/test_user.py
Labels: refactor

#74 refac: refactor delete approved file in repository and add test code
  claon_admin/schema/center.py
  claon_admin/schema/user.py
  claon_admin/service/user.py
  tests/repository/test_center.py
  tests/repository/test_user.py
  tests/service/test_user.py
Labels: refactor

#75 refac: add test case for center, user repository and admin, user service
  claon_admin/service/admin.py
  claon_admin/service/user.py
  tests/repository/test_center.py
  tests/repository/test_user.py
  tests/service/test_admin.py
  tests/service/test_user.py
Labels: refactor
